//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.Web.Metadata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.Web.Metadata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the &lt;Escc.Web.Metadata&gt;&lt;ControlledListXml /&gt;&lt;/Escc.Web.Metadata&gt; configuration section in web.config.
        /// </summary>
        internal static string ErrorConfig {
            get {
                return ResourceManager.GetString("ErrorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;Escc.Web.Metadata&gt;&lt;ControlledListXml /&gt;&lt;/Escc.Web.Metadata&gt; configuration section in web.config does not contain an entry for the controlled list name: {0}.
        /// </summary>
        internal static string ErrorConfigListNotFound {
            get {
                return ResourceManager.GetString("ErrorConfigListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML DOM data must be loaded before this method can be used.
        /// </summary>
        internal static string ErrorDomNotLoaded {
            get {
                return ResourceManager.GetString("ErrorDomNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified document was XML but is not in ESD Taxonomy XML format.
        /// </summary>
        internal static string ErrorNotTaxonomyXml {
            get {
                return ResourceManager.GetString("ErrorNotTaxonomyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EsdTerm object was expected.
        /// </summary>
        internal static string ErrorTermExpected {
            get {
                return ResourceManager.GetString("ErrorTermExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML data must be loaded before this method can be used.
        /// </summary>
        internal static string ErrorXmlNotLoaded {
            get {
                return ResourceManager.GetString("ErrorXmlNotLoaded", resourceCulture);
            }
        }
    }
}
